name: Commit feed to Discord

on:
  push:
    branches:
      - "**"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get commit data
        id: get_data
        run: |
          echo "Repo=${{ github.repository }}" >> $GITHUB_ENV
          echo "Branch=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "Author=${{ github.event.pusher.name }}" >> $GITHUB_ENV
          echo "Timestamp=$(TZ=America/New_York date '+%A %m-%d-%Y %I:%M %p %Z')" >> $GITHUB_ENV
          echo "CommitHash=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV
          echo "CommitMsg=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "Link=https://github.com/${{ github.repository }}/commit/${{ github.sha }}" >> $GITHUB_ENV

      - name: Post to Discord
        env:
         WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo ":white_check_mark: GitHub push detected" > message.txt
          echo "Repo: $Repo" >> message.txt
          echo "Branch: $Branch" >> message.txt
          echo "Author: $Author" >> message.txt
          echo "Time: $Timestamp" >> message.txt
          echo "Commit: $CommitHash $CommitMsg" >> message.txt
          echo "Link: $Link" >> message.txt

          PAYLOAD=$(jq -Rs '{content: .}' < message.txt)
          curl -s -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK"
